services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_MODULES: 'text2vec-ollama' 
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      OLLAMA_API_HOST: 'host.docker.internal:11434'
    volumes:
      - weaviate_data:/var/lib/weaviate
volumes:
  weaviate_data:

