services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_MODULES: 'text2vec-ollama' 
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      OLLAMA_API_ENDPOINT: 'http://host.docker.internal:11434' 
    volumes:
      - weaviate_data:/var/lib/weaviate
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8080/v1/.well-known/ready || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s 
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  rag-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./client:/app/client
    environment:
      OLLAMA_HOST: 'http://host.docker.internal:11434'
      WEAVIATE_URL: 'http://weaviate:8080'
    depends_on:
      weaviate:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  weaviate_data: